### ISSUE TITLE
Start index error masked due to null printstream

### ISSUE THREAD

**Issue by sarthakn7** [Yelp/nrtsearch#136]
Lucene uses a printstream for various logs, but we set this to null in https://github.com/Yelp/nrtsearch/blob/master/src/main/java/com/yelp/nrtsearch/server/luceneserver/ShardState.java#L783 when we set verbose to false. So when an exception is caught here https://github.com/apache/lucene-solr/blob/master/lucene/replicator/src/java/org/apache/lucene/replicator/nrt/ReplicaNode.java#L303 an NPE due to the null printstream is thrown masking the original error. 
The printstream is used by Lucene for nrt replication logs as well which can be quite frequent and which we mostly don't need in production, which is why we don't provide the printstream. We may have to look into a better way to avoid the nrt logs while providing the stream, or raise an issue in Lucene to rethrow the original exception if printstream is null.

**Comment by umeshdangat** [comment]
We could extend java.io.PrintStream class and NoOp the println methods in it. The lucene code in Node.java expects the printStream to be null else calls printstream.println(String) on the replication debug level messages.

Seems like  the lucene base start() method rethrows this exception after logging the stack trace via printStream. Thus in our code we should be able to catch it and log as usual (which we already do for at the topmost rpc/endpoint level )
