### ISSUE TITLE
Dockerize NrtSearch - Optional

### ISSUE THREAD

**Issue by jpizagno** [Yelp/nrtsearch#381]
## Motivation
It would be helpful to have a "dockerized" version of NrtSearch.   This would enable host OS independence, process isolation, dependency clarification, and some management/provider independence. There is more information below.

As a note, I tried running NrtSearch following the instructions in the README.md. It crashed on the first step ("Build Server and Client"), because the wrong version of Java is installed on the host OS. See more information at the end of this Issue.

## Reasoning
Here are more details regarding the motivation to dockerize NrtSearch: 

1. A dockerized version would make **NrtSearch host independent**, assuming that the host has docker installed.  This would enable one to run NrtSearch locally on Mac or Linux machines, along with various flavors of Linux based cloud images.  This will also leave the host OS "clean", or free of NrtSearch dependencies.
2. With a **Docker base image** one could upload the image to dockerhub, or other cloud provider (AWS, GCP, etc..) image repositories. This would make it easier to deploy NrtSearch in various environments.  It would also enable easier integration into orchestration systems such as K8s or OpenShift.
3. Having a dockerized base image would allow **a clear enumeration of the dependencies**.  Gradle does include the application dependencies, but not the host OS dependencies.
4. With a docker base image one could easily run **docker-compose** locally for testing. With a docker-compose version one could also scale up the Replica Nodes with ease. A docker-compose version would also make it easier to start and stop NrtSearch locally.

## Concrete Actions

1. Build new directory at the root level for docker 
2. Build `Dockerfile` files in 3 (or more ) directories for the base image, main node, replica node
3. create `docker-compose.yaml` file along with a `build.sh` and `start.sh` script.

## Example Host OS Dependent Failure
Upon trying to build NrtSearch on my laptop (Dell, Ubuntu 20, i7-6700HQ, Java 8, 16GB RAM), I found this build dependency : 
```
shell nrtsearch$ ./gradlew clean installDist test
...
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> invalid source release: 14

```

**Comment by jpizagno** [comment]
@sarthakn7  I have 2 quick questions regarding this Issue.

1. Would a docker-compose version of nrtSearch function, given that the storage is s3?
2. Would it be better to create a terraform version, using AWS type resources?

**Comment by umeshdangat** [comment]
@jpizagno I assume you want to use docker-compose for testing in a local environment as you mentioned before ?

> With a docker base image one could easily run docker-compose locally for testing. With a docker-compose version one could also scale up the Replica Nodes with ease. A docker-compose version would also make it easier to start and stop NrtSearch locally.

While nrtsearch does backup and bootstrap previous indexes from s3,  that is only needed to "persist state" in case you are not already having access to the same disk for example when running in a containerized environment. That is your index can still be restored to the point of your last `commit`  if you restart the jvm and point to the same disk. However given you plan to run it in a containerized environment (and I assume not use EBS which is probably a good idea s well) we have to use s3 creds and s3 is the only currently supported remote data storage as of today.

Generally speaking, we could make the backup/restore APIs more abstract and allow users to support other forms of remote data storage e.g. google cloud storage, nfs,  etc. We probably do want to stay away from making nrtsearch to aws centric.

**Comment by jpizagno** [comment]
@umeshdangat  Thanks for the information.  I will start to work on a docker-compose.yaml file.

What is the setup/config in production?

**Comment by sarthakn7** [comment]
Done in #417
