### ISSUE TITLE
Logging configuration

### ISSUE THREAD

**Issue by frotsch** [Yelp/nrtsearch#403]
How can the loglevel be adjusted? The log4j configuration is baked into the jar file and there is no config property to override this (at least I did not find anything).

**Comment by jedrazb** [comment]
Hey 👋  you should be able to edit the logging configuration in this file: https://github.com/Yelp/nrtsearch/blob/master/src/main/resources/log4j2.yaml

**Comment by frotsch** [comment]
IMHO this only works when nrtsearch is build after a change. I like to change when executing `lucene-server` (or even better: when already running).

Assume I have nrtsearch running in production on ERROR loglevel. Then people start complaining about stuff. To figure out whats going on I want to temporarily change the loglevel to DEBUG (ideally without restarting).

**Comment by sarthakn7** [comment]
We use log4j2 for logging so you can override the configuration like this: `-Dlog4j.configurationFile=path/to/log4j2.xml`
Ref: https://logging.apache.org/log4j/2.x/manual/configuration.html

**Comment by sarthakn7** [comment]
Closing this out, feel free to reopen if this doesn't solve your issue.
