### ISSUE TITLE
remove rootDir param from createIndex

### ISSUE THREAD

**Issue by umeshdangat** [Yelp/nrtsearch#50]
Although https://github.com/Yelp/platypus/pull/43 removed the need to pass in explicit indexDir name on each createIndex call, we still send this in. We would need to remove this from the supporting clients as well.

**Comment by deansher** [comment]
This is currently very confusing for a new user:

- The examples in `README.md` show passing a `--rootDir` to `createIndex`.
- The help text for `createIndex` also documents this flag.
- But the flag doesn't do anything.

**Comment by deansher** [comment]
Gack, it's worse than that! The flag is required but does nothing.
```
+ lucene-client createIndex -i queryIdx
Missing required option '--rootDir=<rootDir>'
Usage: lucene-client createIndex -d=<rootDir> -i=<indexName>
Creates the index per the specified name
  -d, --rootDir=<rootDir>   Name of the directory where index is to be created
  -i, --indexName=<indexName>
                            Name of the index to be created
```
