### ISSUE TITLE
Pin grpc-gateway version

### ISSUE THREAD

**Issue by sarthakn7** [Yelp/nrtsearch#91]
We currently get the latest code. Would be better to pin to a release version.

**Comment by jedrazb** [comment]
From what I understand, package versioning is supported by [go modules](https://blog.golang.org/using-go-modules) further described [here](https://dev.to/maelvls/why-is-go111module-everywhere-and-everything-about-go-modules-24k). Using `GOPATH` seems to be older approach to managing project dependencies. Pinning version of `grpc-gateway` would require us to move to use `go modules` which would allow to get dependencies like: `go get module@version`. If there is nothing blocking us from moving to go modules I can prepare a PR for that.
